"""
HTML Logger for KG-Augmented Generation Test Results

This module provides functionality to generate colored HTML reports
for tracking LLM interactions with knowledge graphs.
"""

import os
import re
import json
from datetime import datetime
from typing import List, Dict, Any, Optional


class HTMLLogger:
    """HTML logger for KG-augmented generation trajectories."""
    
    def __init__(self, output_dir: str = "test_results"):
        self.output_dir = output_dir
        self.logs = []
        self.current_test_case = None
        self.test_start_time = None
        
        # Ensure output directory exists
        os.makedirs(output_dir, exist_ok=True)
        
    def start_test_case(self, test_case: Dict[str, Any]):
        """Start logging a new test case."""
        self.current_test_case = test_case
        self.test_start_time = datetime.now()
        
    def log_system_message(self, message: str):
        """Log a system message."""
        self._add_log("system", message)
        
    def log_question(self, question: str):
        """Log a question."""
        self._add_log("question", question)
        
    def log_search_query(self, query: str):
        """Log a search query."""
        self._add_log("search", query)
        
    def log_kg_result(self, result: str):
        """Log a KG retrieval result."""
        self._add_log("kg_result", result)
        
    def log_llm_response(self, response: str):
        """Log an LLM response."""
        self._add_log("llm_response", response)
        
    def log_answer(self, answer: str):
        """Log a final answer."""
        self._add_log("answer", answer)
        
    def log_error(self, error: str):
        """Log an error message."""
        self._add_log("error", error)
        
    def log_debug(self, debug_info: str):
        """Log debug information."""
        self._add_log("debug", debug_info)
        
    def log_reward_info(self, reward_data):
        """Log reward scoring information."""
        if isinstance(reward_data, dict):
            self._add_log("reward", json.dumps(reward_data, indent=2))
        else:
            # Allow raw HTML for reward display
            self._add_log("reward_html", str(reward_data))
    
    def log_raw_html(self, html_content: str):
        """Log raw HTML content without escaping."""
        self._add_log("raw_html", html_content)
        
    def _add_log(self, log_type: str, content: str):
        """Add a log entry."""
        timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
        self.logs.append({
            "timestamp": timestamp,
            "type": log_type,
            "content": content,
            "test_case_id": self.current_test_case["id"] if self.current_test_case else None
        })
        
    def save_html_report(self, filename: Optional[str] = None) -> str:
        """Save the complete HTML report."""
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"kg_test_report_{timestamp}.html"
            
        filepath = os.path.join(self.output_dir, filename)
        
        html_content = self._generate_html_report()
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
            
        return filepath
        
    def _generate_html_report(self) -> str:
        """Generate the complete HTML report."""
        # Group logs by test case
        test_cases = {}
        for log in self.logs:
            test_case_id = log["test_case_id"] or "general"
            if test_case_id not in test_cases:
                test_cases[test_case_id] = []
            test_cases[test_case_id].append(log)
            
        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KG-Augmented Generation Test Report</title>
    <style>
        {self._get_css_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🧠 KG-Augmented Generation Test Report</h1>
            <p class="timestamp">Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        </header>
        
        <div class="summary">
            <h2>📊 Test Summary</h2>
            <ul>
                <li><strong>Total Test Cases:</strong> {len([tc for tc in test_cases.keys() if tc != "general"])}</li>
                <li><strong>Total Log Entries:</strong> {len(self.logs)}</li>
                <li><strong>Test Duration:</strong> {self._calculate_total_duration()}</li>
            </ul>
        </div>
        
        <div class="test-cases">
            {self._generate_test_cases_html(test_cases)}
        </div>
        
        <footer>
            <p>Generated by KG-Augmented Generation Test Framework</p>
        </footer>
    </div>
    
    <script>
        {self._get_javascript()}
    </script>
</body>
</html>
"""
        return html
        
    def _get_css_styles(self) -> str:
        """Get CSS styles for the HTML report."""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f5f5f5;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }
        
        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 10px;
            margin-bottom: 30px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
        }
        
        header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }
        
        .timestamp {
            opacity: 0.9;
            font-size: 1.1em;
        }
        
        .summary {
            background: white;
            padding: 25px;
            border-radius: 10px;
            margin-bottom: 30px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.05);
        }
        
        .summary h2 {
            color: #4a5568;
            margin-bottom: 15px;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 10px;
        }
        
        .summary ul {
            list-style: none;
        }
        
        .summary li {
            padding: 8px 0;
            border-bottom: 1px solid #f7fafc;
        }
        
        .test-case {
            background: white;
            margin-bottom: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.05);
            overflow: hidden;
        }
        
        .test-case-header {
            background: linear-gradient(135deg, #4299e1 0%, #3182ce 100%);
            color: white;
            padding: 20px;
            cursor: pointer;
            transition: background 0.3s;
        }
        
        .test-case-header:hover {
            background: linear-gradient(135deg, #3182ce 0%, #2c5282 100%);
        }
        
        .test-case-header h3 {
            font-size: 1.5em;
            margin-bottom: 5px;
        }
        
        .test-case-content {
            display: none;
            padding: 0;
        }
        
        .test-case-content.active {
            display: block;
        }
        
        .log-entry {
            padding: 15px 25px;
            border-bottom: 1px solid #e2e8f0;
            transition: background 0.2s;
        }
        
        .log-entry:hover {
            background-color: #f7fafc;
        }
        
        .log-entry:last-child {
            border-bottom: none;
        }
        
        .log-timestamp {
            font-size: 0.85em;
            color: #718096;
            margin-bottom: 5px;
        }
        
        .log-content {
            font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
            white-space: pre-wrap;
            word-wrap: break-word;
        }
        
        /* Log type specific styles */
        .log-system {
            border-left: 4px solid #3182ce;
            background-color: #ebf8ff;
        }
        
        .log-question {
            border-left: 4px solid #d69e2e;
            background-color: #fffbeb;
        }
        
        .log-search {
            border-left: 4px solid #38b2ac;
            background-color: #e6fffa;
        }
        
        .log-kg_result {
            border-left: 4px solid #48bb78;
            background-color: #f0fff4;
        }
        
        .log-llm_response {
            border-left: 4px solid #805ad5;
            background-color: #faf5ff;
        }
        
        .log-answer {
            border-left: 4px solid #e53e3e;
            background-color: #fed7d7;
            font-weight: bold;
        }
        
        .log-error {
            border-left: 4px solid #e53e3e;
            background-color: #fed7d7;
            color: #c53030;
        }
        
        .log-debug {
            border-left: 4px solid #a0aec0;
            background-color: #f7fafc;
            opacity: 0.8;
            font-size: 0.9em;
        }
        
        .log-reward {
            border-left: 4px solid #ed8936;
            background-color: #fffaf0;
        }
        
        .reward-score {
            display: inline-block;
            background: linear-gradient(135deg, #ed8936 0%, #dd6b20 100%);
            color: white;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.9em;
            font-weight: bold;
            margin-left: 10px;
        }
        
        .collapsible-btn {
            background: none;
            border: none;
            color: white;
            font-size: 1.2em;
            cursor: pointer;
            float: right;
            transition: transform 0.3s;
        }
        
        .collapsible-btn.active {
            transform: rotate(180deg);
        }
        
        footer {
            text-align: center;
            padding: 30px;
            color: #718096;
            font-style: italic;
        }
        
        @media (max-width: 768px) {
            .container {
                padding: 10px;
            }
            
            header h1 {
                font-size: 2em;
            }
            
            .log-entry {
                padding: 10px 15px;
            }
        }
        """
        
    def _get_javascript(self) -> str:
        """Get JavaScript for interactive features."""
        return """
        document.addEventListener('DOMContentLoaded', function() {
            // Make test case headers collapsible
            const headers = document.querySelectorAll('.test-case-header');
            headers.forEach(header => {
                header.addEventListener('click', function() {
                    const content = this.nextElementSibling;
                    const btn = this.querySelector('.collapsible-btn');
                    
                    content.classList.toggle('active');
                    btn.classList.toggle('active');
                });
            });
            
            // Auto-expand first test case
            const firstContent = document.querySelector('.test-case-content');
            const firstBtn = document.querySelector('.collapsible-btn');
            if (firstContent && firstBtn) {
                firstContent.classList.add('active');
                firstBtn.classList.add('active');
            }
        });
        """
        
    def _generate_test_cases_html(self, test_cases: Dict[str, List[Dict]]) -> str:
        """Generate HTML for all test cases."""
        html_parts = []
        
        for test_case_id, logs in test_cases.items():
            if test_case_id == "general":
                continue  # Skip general logs for now
                
            html_parts.append(f"""
            <div class="test-case">
                <div class="test-case-header" onclick="toggleTestCase(this)">
                    <h3>🧪 Test Case: {test_case_id}</h3>
                    <button class="collapsible-btn">▼</button>
                </div>
                <div class="test-case-content">
                    {self._generate_logs_html(logs)}
                </div>
            </div>
            """)
            
        return "\n".join(html_parts)
        
    def _generate_logs_html(self, logs: List[Dict]) -> str:
        """Generate HTML for a list of log entries."""
        html_parts = []
        
        for log in logs:
            content = self._format_log_content(log)
            html_parts.append(f"""
            <div class="log-entry log-{log['type']}">
                <div class="log-timestamp">{log['timestamp']}</div>
                <div class="log-content">{content}</div>
            </div>
            """)
            
        return "\n".join(html_parts)
        
    def _format_log_content(self, log: Dict) -> str:
        """Format log content with appropriate styling."""
        content = str(log['content'])
        log_type = log['type']
        
        # For certain log types, allow raw HTML without escaping
        if log_type in ["raw_html", "reward_html", "llm_response"]:
            # Don't escape HTML for these types
            pass
        else:
            # HTML escape the content for safety
            content = content.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        
        # Add special formatting for different log types
        if log_type == "search":
            content = f"🔍 <strong>Search Query:</strong> {content}"
        elif log_type == "kg_result":
            content = f"📊 <strong>KG Result:</strong> {content}"
        elif log_type == "answer":
            content = f"✅ <strong>Final Answer:</strong> {content}"
        elif log_type == "error":
            content = f"❌ <strong>Error:</strong> {content}"
        elif log_type == "llm_response":
            content = f"🤖 <strong>LLM Response:</strong> {content}"
        elif log_type == "reward_html":
            content = f"🏆 <strong>Reward Info:</strong> {content}"
        elif log_type == "raw_html":
            # Raw HTML without any additional formatting
            pass
        elif log_type == "reward":
            # Try to parse JSON for better formatting
            try:
                reward_data = json.loads(log['content'])
                if isinstance(reward_data, dict) and 'score' in reward_data:
                    score = reward_data.get('score', 0)
                    content = f"🏆 <strong>Reward Score:</strong> <span class='reward-score'>{score:.3f}</span><br><pre>{json.dumps(reward_data, indent=2)}</pre>"
                else:
                    content = f"🏆 <strong>Reward Info:</strong><br><pre>{content}</pre>"
            except:
                content = f"🏆 <strong>Reward Info:</strong><br><pre>{content}</pre>"
        elif log_type == "system":
            content = f"⚙️ <strong>System:</strong> {content}"
        elif log_type == "question":
            content = f"❓ <strong>Question:</strong> {content}"
        elif log_type == "debug":
            content = f"🐛 <strong>Debug:</strong> {content}"
            
        return content
        
    def _calculate_total_duration(self) -> str:
        """Calculate the total test duration."""
        if not self.logs:
            return "N/A"
            
        try:
            first_log = self.logs[0]
            last_log = self.logs[-1]
            
            # This is a simplified duration calculation
            # In a real implementation, you'd track actual start/end times
            return f"~{len(self.logs)} log entries"
        except:
            return "N/A"
